version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-image:
                - "node:14"
                - "node:16"
                - "node:18"

  coveralls-upload:
      jobs:
        - coveralls-upload

jobs:
  test:
    parameters:
      node-image:
        type: string
    docker:
      - image: << parameters.node-image >>
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm i -g npm@9
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Run tests
          command: npm run test

  coveralls-upload:
    docker:
      - image: "node:18"
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm i -g npm@9
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Run coveralls
          command: npm run coveralls
      - coveralls/upload
